---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---
# read data
```{r}
dat = read.csv("Advertising.csv")
```

# 1. simple LR
```{r}
model = lm(Sales~TV, data = dat)
summary(model)
```

```{r}
model$coefficients
```
```{r}
confint.lm(model,level = 0.95)
```
```{r}
model$residuals
model$fitted.values
```

# 2. multiple LR

## model-1: Sales~TV
```{r}
model1 = lm(Sales~TV, data=dat)
summary(model1)
```
## model-2: Sales~Radio

```{r}
model2 = lm(Sales~Radio, data = dat)
summary(model2)
```
## model-3: Sales~Newspaper
```{r}
model3 = lm(Sales~Newspaper, data=dat)
summary(model3)
```

## model 4: multiple LR
```{r}
# model4 = lm(Sales~TV+Radio+Newspaper, data = dat)

model4 = lm(Sales~., data=dat)

summary(model4)
```
```{r}
cor(dat)
```

```{r}
plot(dat$TV,dat$Radio)
plot(dat$TV, dat$Newspaper)
plot(dat$Radio, dat$Newspaper)
```

## model 5: Sales~TV+Radio

```{r}
model5 = lm(Sales~TV+Radio, data = dat)

model5 = lm(Sales~.-Newspaper, data = dat)

summary(model5)
```


## why R-sq is not good.
```{r}
m1 = lm(Sales~TV, data=dat)

smry1 = summary(m1)
smry1$r.squared
smry1$adj.r.squared
```

```{r}
set.seed(0201)

x = runif(200)*20
x1 = runif(200)*20

m2 = lm(Sales~TV+x+x1, data=dat)

smry2 = summary(m2)
smry2$r.squared
smry2$adj.r.squared
```
## predict, CI, PI
```{r}
model4 = lm(Sales~., data=dat)

new_data = data.frame(TV = c(200, 210), 
                      Radio = c(20, 19), 
                      Newspaper= c(10, 12)
                      )

predict(model4, newdata = new_data)

predict(model4, newdata = new_data,interval = "confidence", level=0.95)

predict(model4, newdata = new_data,interval = "predict", level=0.95)
```

# Qualitative Predictors
```{r}
library(ISLR2)

model.own = lm(Balance~Own, data=Credit)
summary(model.own)
```
```{r}
model.student = lm(Balance~Student, data=Credit)
summary(model.student)
```
```{r}
model.region = lm(Balance~Region, data = Credit)
summary(model.region)
```
## relevel
```{r}
Region.1 = relevel(as.factor(Credit$Region), ref = 'West')

# model.region.1 = lm(Balance~Region.1, data=Credit)

model.region.1 = lm(Credit$Balance~Region.1)

summary(model.region.1)
```
# Interaction

```{r}
Advertising = read.csv('Advertising.csv')

pairs(Advertising)
```

```{r}
# model.interaction = lm(Sales~TV+Radio+TV:Radio, data = Advertising)

model.interaction = lm(Sales~TV*Radio, data = Advertising)

summary(model.interaction)
```
# non-linear relationship
```{r}
plot(Auto$horsepower, Auto$mpg)
```

```{r}
model.nonlinear = lm(mpg~horsepower+I(horsepower^2),data = Auto )

summary(model.nonlinear)
```
# other considerations
## 1. nonlinearity

```{r}
model = lm(mpg~.-name, data=Auto)
summary(model)
```
### Residual analysis
```{r}
hist(model$residuals)
mean(model$residuals)

```
## 3. non-constant variance
```{r}
plot(model$fitted.values, model$residuals)
```

```{r}
model.trans = lm(log(mpg)~.-name, data=Auto)

plot(model.trans$fitted.values, model.trans$residuals)
```



## 6 Collinearity
```{r}
pairs(Auto[,1:8])
```

```{r}
# displacement
m.disp = lm(displacement~.-name-mpg, data = Auto)

smry = summary(m.disp)

# smry$r.squared

vif.disp = 1/(1-smry$r.squared)

vif.disp
```

```{r}
model = lm(mpg~.-name-displacement, data = Auto)
summary(model)
```







