---
title: "R Notebook"
output: html_notebook
---
```{r}
library(ISLR2)
library(tree)
```


```{r}
set.seed(1)
N = nrow(Boston)
train.indice = sample(1:N, N/2)
test.indice = (-train.indice)

train.set = Boston[train.indice, ]
test.set = Boston[test.indice, ]

```

# Create a large tree
```{r}
tree.boston = tree(medv~., data = train.set)
summary(tree.boston)
```
```{r}
plot(tree.boston)
text(tree.boston)
```
# Prune the tree
```{r}
set.seed(1)

cv.boston = cv.tree(tree.boston, K=10)

cv.boston$k

```
```{r}
names(cv.boston)
cv.boston$size
cv.boston$dev

plot(cv.boston$size, cv.boston$dev, type="b")
```

```{r}
i = which.min(cv.boston$dev)

i
cv.boston$size[i]
```
## prune the tree
```{r}
prune.boston = prune.tree(tree.boston, best = 6)

plot(prune.boston)
text(prune.boston)
```
## prediction
```{r}
predict(prune.boston, newdata = train.set[1, ])
```

## test mse using pruned tree
```{r}
y_pred_prune = predict(prune.boston, newdata = test.set)
mean((test.set$medv - y_pred_prune)^2)

```
## test mse using original big tree
```{r}
y_pred_0 = predict(tree.boston, newdata = test.set)
mean((test.set$medv - y_pred_0)^2)
```









